name: Checkout Ref
description: Updates and checks out a given ref for an existing repository
inputs:
  repository-path:
    description: 'The path to the repository to update and check out the ref'
    required: true
    default: '.'
  ref:
    description: 'The git ref to check out'
    required: true
outputs:
  sha:
    description: 'The SHA of the checked out ref'
    value: ${{ steps.checkout.outputs.sha }}
runs:
  using: composite
  steps:
    - shell: bash
      id: checkout
      working-directory: ${{ inputs.repository-path }}
      run: |
        git fetch --all --tags

        if git ls-remote --exit-code --heads origin ${{ inputs.ref }}; then  # If the ref is a branch
          echo "Checking out the branch ${{ inputs.ref }} at the latest commit"
          git checkout -B ${{ inputs.ref }} origin/${{ inputs.ref }}
        else  # checkout the tag/commit
          echo "Checking out the tag/commit ${{ inputs.ref }}"
          git checkout ${{ inputs.ref}}
        fi

        echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
