name: Spack Instance

# docker compose ignores 'x-' keys, but they can be used as anchors (&common-args)
# to reduce duplication in the file
x-common-args: &common-args
  OS: ${OS}
  SPACK_VERSION: ${SPACK_VERSION}
services:
  upstream:
    container_name: Upstream
    image: ghcr.io/access-nri/build-ci-upstream:${OS}-${SPACK_VERSION}-${IMAGE_VERSION}
    tty: true
    build:
      context: .
      target: upstream
      args:
        <<: *common-args
        SOURCE_COMPILERS_SPACK_MANIFEST: upstream/compilers.spack.yaml
        SOURCE_PACKAGES_SPACK_MANIFEST: upstream/packages.spack.yaml
        SPACK_REPO_VERSION: access/releases/${SPACK_VERSION}-admin
      secrets:
        - oci-username
        - oci-password
        - oci-url
    volumes:
      - upstream:/opt/release:rw
      - buildcache:/opt/runner_set_buildcache:rw

  runner:
    container_name: Runner
    image: ghcr.io/access-nri/build-ci-runner:${OS}-${SPACK_VERSION}-${IMAGE_VERSION}
    tty: true
    depends_on:
    - upstream
    build:
      context: .
      target: runner
      args:
        <<: *common-args
        SPACK_REPO_VERSION: access/releases/${SPACK_VERSION}
    volumes:
      - upstream:/opt/release:ro
      - buildcache:/opt/runner_set_buildcache:rw

volumes:
  upstream:
  buildcache:

secrets:
  oci-username:
    environment: BUILD_CI_BUILDCACHE_OCI_USERNAME
  oci-password:
    environment: BUILD_CI_BUILDCACHE_OCI_PASSWORD
  oci-url:
    environment: BUILD_CI_BUILDCACHE_OCI_URL
