# NOTE: Keep an eye on:
#       $SPACK_ROOT/share/spack/templates/container/rockylinux_8.dockerfile
FROM rockylinux:8.8

# csh currently required for some build scripts e.g. MOM5
RUN dnf update -y \
 && dnf -y group install "Development Tools" \
 && dnf -y install \
    gcc-gfortran \
    git \
    jq \
    python3 \
    python3-pip \
    csh \
 && rm -rf /var/cache/dnf \
 && dnf clean all

RUN pip3 install --no-cache-dir boto3==1.23.10
