FROM ubuntu:20.04

# Install spack dependencies
RUN apt-get update && apt-get install -y\
    git\
    python3\
    build-essential\
    curl\
    gfortran

# Install spack
RUN git clone -c feature.manyFiles=true https://github.com/spack/spack.git /opt/spack --branch v0.19.0 --single-branch --depth=1
RUN ln -s /opt/spack/bin/spack /bin

# Set up ACCESS spack package repo
RUN git clone https://github.com/ACCESS-NRI/spack_packages.git /opt/spack_packages
RUN spack repo add /opt/spack_packages
