name: Build and Push Image as Spack Release
on:
  workflow_call:
    inputs:
      container-registry:
        required: true
        type: string
      container-name:
        required: true
        type: string
      dockerfile-directory:
        required: true
        type: string
      dockerfile-name:
        required: true
        type: string
      build-args:
        required: false
        type: string
        default: ""
      package-name:
        required: true
        type: string
    secrets:
      build-secrets:
        required: false
jobs:
  build-and-push-image-as-release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Buildx is currently required to use a subdirectory w/ build-push-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.container-registry }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.container-registry }}/${{ inputs.container-name }}
        flavor: |
          latest=true

    - name: Build Docker image
      id: build-push-image
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:${{ inputs.dockerfile-directory }}"
        build-args: ${{ inputs.build-args }}
        secrets: ${{ secrets.build-secrets }}
        file: ${{ inputs.dockerfile-name }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        load: true
    
    - name: Get Spack Environment Info From Docker Image
      id: spackenv
      run: docker run --rm ${{ steps.build-push-image.outputs.imageid }} -v environment:/opt/spack/var/spack/environments/${{ inputs.package-name }}

    - name: Push Docker Image As Package
      uses: docker/build-push-action@v3
      with: 
        context: "{{defaultContext}}:${{ inputs.dockerfile-directory }}"
        build-args: ${{ inputs.build-args }}
        secrets: ${{ secrets.build-secrets }}
        file: ${{ inputs.dockerfile-name }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        push: true

    - name: Push Spack Env as Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "environment/spack.*"
