name: Build and push access-nri/build images

on:
  workflow_dispatch:
    inputs:
      spack-packages-build-required:
        required: true
        default: true
        type: boolean
        description: "A flag to note if building a new spack_packages image at the below version is required"
      spack-packages-version:
        required: true
        type: string
        default: "main"
        description: "Either a git tag or branch name for the ACCESS-NRI/spack_packages repository, which defaults to the main branch"
      model:
        required: true
        type: choice
        default: "all"
        options:
          - access-om2
          - access-om3
          - all

jobs:
  base-spack-build-and-push-image:
    if: inputs.spack-packages-build-required
    uses: access-nri/build-ci/.github/workflows/build-and-push-image.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/base-spack-${{ github.event.inputs.spack-packages-version }}
      dockerfile-directory: containers
      dockerfile-name: Dockerfile.base-spack
      build-args: "SPACK_PACKAGES_REPO_VERSION=${{ github.event.inputs.spack-packages-version }}"
    secrets:
      build-secrets: |
        "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}"
        "S3_ACCESS_KEY_SECRET=${{ secrets.S3_ACCESS_KEY_SECRET }}"
        "access-nri.priv=${{ secrets.BUILDCACHE_KEY_PRIVATE }}"
        "access-nri.pub=${{ secrets.BUILDCACHE_KEY_PUBLIC }}"
    permissions:
      contents: read
      packages: write
    
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      model: ${{ steps.get-model.outputs.model }}
      compiler: ${{ steps.get-compiler.outputs.compiler }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine correct model(s) to build
        id: get-model
        run: |
          if [[ ${{ inputs.model }} -eq "all" ]]; then
            echo "model=[access-om2, access-om3]" >> $GITHUB_OUTPUT
          else
            echo "model=[${{ inputs.model }}]" >> $GITHUB_OUTPUT
          fi
      - name: Determine compilers to build
        id: get-compiler
        run: echo "compiler=`cat containers/compilers.yaml`" >> $GITHUB_OUTPUT
  
  model-build-and-push-image:
    needs:
      - base-spack-build-and-push-image
      - generate-matrix
    if: always()
    strategy:
      fail-fast: false
      matrix:
        model: ${{ needs.generate-matrix.outputs.model }}
        compiler: ${{ needs.generate-matrix.outputs.compiler }}
    uses: access-nri/build-ci/.github/workflows/build-and-push-image.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/build-${{ matrix.model}}-${{ matrix.compiler.name }}${{ matrix.compiler.version }}-${{ inputs.spack-packages-version }}
      dockerfile-directory: containers
      dockerfile-name: Dockerfile.${{ matrix.model }}
      build-args: |
        # TODO: Probably shouldn't hard code base image path
        "BASE_IMAGE=ghcr.io/access-nri/base-spack-${{ github.event.inputs.spack-packages-version }}:latest"
        "COMPILER_NAME=${{ matrix.compiler.name }}"
        "COMPILER_PACKAGE=${{ matrix.compiler.package }}"
        "COMPILER_VERSION=${{ matrix.compiler.version }}"
    permissions:
      contents: read
      packages: write
