name: Build and push access-nri/base-spack image

on:
  workflow_dispatch:
    inputs:
      spack-packages-version:
        required: true
        type: string
        default: "main"
        description: "Either a git commit hash, a tag, or a branch name for the ACCESS-NRI/spack_packages repository, which defaults to the main branch"

jobs:
  build-and-push-image:
    uses: access-nri/workflows/.github/workflows/build-and-push-image.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/base-spack-${{ github.event.inputs.spack-packages-version }}
      dockerfile-directory: containers
      dockerfile-name: Dockerfile.base-spack
      build-args: "SPACK_PACKAGES_VERSION=${{ github.event.inputs.spack-packages-version }}"
    secrets: 
      build-secrets: |
        "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}"
        "S3_ACCESS_KEY_SECRET=${{ secrets.S3_ACCESS_KEY_SECRET }}"
        "access-nri.priv=${{ secrets.BUILDCACHE_KEY_PRIVATE }}"
        "access-nri.pub=${{ secrets.BUILDCACHE_KEY_PUBLIC }}"
    permissions:
      contents: read
      packages: write
