name: Build and push package build image

on:
  workflow_call:
    inputs:
      container-registry:
        required: true
        type: string
      container-path:
        required: true
        type: string
      dockerfile-directory:
        required: true
        type: string

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Buildx is currently required to use a subdirectory w/ build-push-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ inputs.container-registry }}
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ inputs.container-registry }}/${{ inputs.container-path }}
        flavor: |
          latest=true

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: "{{defaultContext}}:${{ inputs.dockerfile-directory }}"
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
