name: Build and push access-nri/build images

on:
  workflow_dispatch:
    inputs:
      spack-packages-build-required:
        required: true
        default: true
        type: boolean
        description: "A flag to note if building a new spack_packages image at the below version is required"
      spack-packages-version:
        required: true
        type: string
        default: "main"
        description: "Either a git tag or branch name for the ACCESS-NRI/spack_packages repository, which defaults to the main branch"

jobs:
  base-spack-build-and-push-image:
    if: inputs.spack-packages-build-required
    uses: access-nri/build-ci/.github/workflows/build-and-push-image.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/base-spack-${{ github.event.inputs.spack-packages-version }}
      dockerfile-directory: containers
      dockerfile-name: Dockerfile.base-spack
      build-args: "SPACK_PACKAGES_REPO_VERSION=${{ github.event.inputs.spack-packages-version }}"
    secrets:
      build-secrets: |
        "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}"
        "S3_ACCESS_KEY_SECRET=${{ secrets.S3_ACCESS_KEY_SECRET }}"
        "access-nri.priv=${{ secrets.BUILDCACHE_KEY_PRIVATE }}"
        "access-nri.pub=${{ secrets.BUILDCACHE_KEY_PUBLIC }}"
    permissions:
      contents: read
      packages: write

  model-build-and-push-image:
    needs:
      - base-spack-build-and-push-image
    if: needs.base-spack-build-and-push-image.result == 'success' || needs.base-spack-build-and-push-image.result == 'skipped'
    strategy:
      fail-fast: false
      matrix:
        compiler: [
          {
            name: "intel",
            package: "intel-oneapi-compilers",
            version: "2021.1.2",
          },
        ]
    uses: access-nri/build-ci/.github/workflows/build-and-push-image.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/build-${{ matrix.compiler.name }}${{ matrix.compiler.version }}-${{ github.event.inputs.spack-packages-version }}
      dockerfile-directory: containers
      dockerfile-name: Dockerfile.build
      build-args: |
        # TODO: Probably shouldn't hard code base image path
        "BASE_IMAGE=ghcr.io/access-nri/base-spack-${{ github.event.inputs.spack-packages-version }}:latest"
        "COMPILER_NAME=${{ matrix.compiler.name}}"
        "COMPILER_PACKAGE=${{ matrix.compiler.package}}"
        "COMPILER_VERSION=${{ matrix.compiler.version}}"
    permissions:
      contents: read
      packages: write
