name: Build package

on:
  workflow_call:
    inputs:
      container-registry:
        required: true
        type: string
      container-name:
        required: true
        type: string
      package-name:
        required: true
        type: string
      compiler-name:
        required: true
        type: string
      compiler-version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    container:
      image: ${{ inputs.container-registry }}/${{ inputs.container-name }}:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Build package via spack
      run: |
        spack -d install --only package --no-checksum ${{ inputs.package-name }}@$GITHUB_REF_NAME%${{ inputs.compiler-name }}@${{ inputs.compiler-version }}
      if: github.event_name != 'pull_request'

    # Workaround for this issue: https://github.com/github/docs/issues/15319
    # In the case of a pull request, we need to use GITHUB_HEAD_REF to get the
    # correct branch name
    - name: Build package via spack
      run: |
        spack -d install --only package --no-checksum ${{ inputs.package-name }}@$GITHUB_HEAD_REF%${{ inputs.compiler-name }}@${{ inputs.compiler-version }}
      if: github.event_name == 'pull_request'

    # Install and launch interactive debugging on build failure
    - name: Install tmate on failure
      run: |
        dnf -y install epel-release
        dnf -y install libevent-devel ncurses-devel msgpack-devel libssh-devel
        git clone https://github.com/tmate-io/tmate.git
        cd tmate
        ./autogen.sh
        ./configure
        make
        make install
      if: ${{ failure() }}

    - name: Debug with tmate on failure
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
      with:
        install-dependencies: false
