name: Build package

on:
  workflow_call:
    inputs:
      container-registry:
        required: true
        type: string
      container-name:
        required: true
        type: string
      package-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    container:
      image: ${{ inputs.container-registry }}/${{ github.repository_owner }}/${{ inputs.container-name }}:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Build package via spack
      run: spack -v install --only package --no-checksum ${{ inputs.package-name }}@$GITHUB_REF_NAME
      if: github.event_name != 'pull_request'

    # Workaround for this issue: https://github.com/github/docs/issues/15319
    # In the case of a pull request, we need to use GITHUB_HEAD_REF to get the
    # correct branch name
    - name: Build package via spack
      run: spack -v install --only package --no-checksum ${{ inputs.package-name }}@$GITHUB_HEAD_REF
      if: github.event_name == 'pull_request'
