name: Build package

on:
  workflow_call:
    inputs:
      container-registry:
        required: true
        type: string
      container-name:
        required: true
        type: string
      package-name:
        required: true
        type: string
      compiler-name:
        required: true
        type: string
      compiler-version:
        required: true
        type: string
      spack-packages-version:
        required: false
        type: string
        description: Either a git tag or branch name for the ACCESS-NRI/spack_packages repository, which defaults to the main branch
        default: main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: read

    container:
      image: ${{ inputs.container-registry }}/${{ inputs.container-name }}-${{ inputs.spack-packages-version }}:latest
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Get correct ref
      run: echo "GH_REF=${{ github.event_name == 'pull_request' }} && ${{ github.head_ref }} || ${{ github.ref_name }}" >> $GITHUB_ENV
    
    - name: Activate environment
      run: spack env activate ${{ inputs.package-name }}
    
    - name: Build package via spack
      run: spack -d install --add --only package --fail-fast --no-checksum ${{ inputs.package-name }}@=$GH_REF%${{ inputs.compiler-name }}@${{ inputs.compiler-version }}
    
    - name: Generate lockfile
      run: |
        cd /opt/spack/var/spack/environments/${{ inputs.package-name }}
        cp spack.lock ${{ inputs.package-name }}.original.spack.lock

    - name: Generate force-concretized lockfile
      if: failure()
      run: |
        cd /opt/spack/var/spack/environments/${{ inputs.package-name }}
        spack -d concretize --force
        cp spack.lock ${{ inputs.package-name }}.force.spack.lock

    - name: Upload lockfiles
      uses: actions/upload-artifact@v3
      with: 
        name: lockfile-output
        path: /opt/spack/var/spack/environments/${{ inputs.package-name }}/${{ inputs.package-name }}.*.spack.lock
        

    # Install and launch interactive debugging on build failure
    - name: Install tmate on failure
      run: |
        dnf -y install epel-release
        dnf -y install libevent-devel ncurses-devel msgpack-devel libssh-devel
        git clone https://github.com/tmate-io/tmate.git
        cd tmate
        ./autogen.sh
        ./configure
        make
        make install
      if: ${{ failure() }}

    - name: Debug with tmate on failure
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
      with:
        install-dependencies: false
