name: CI
run-name: CI Test ${{ github.repository }} at ${{ github.event.number }} (${{ github.sha }})
on:
  workflow_call:
    inputs:
      spack-manifest-repository:
        required: false
        type: string
        default: ${{ github.repository }}
        description: |
          The repository containing the spack manifest to install.
          By default, this is the caller model component repository, which will work for most use-cases.
          For example: ACCESS-NRI/access-test-component.
      spack-manifest-repository-ref:
        required: false
        type: string
        # If the inputs.spack-manifest-repository is the same as the caller repo, use the same heuristic as inputs.ref (use the caller SHA), otherwise use the default ref
        # Unfortunately, we can't set expressions as defaults yet, so this is set in the step that checks out the manifest repository
        # default: ${{ inputs.spack-manifest-repository == github.repository && (github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha) || '' }}
        description: |
          The branch, tag, or commit SHA of the inputs.spack-manifest-repository to use.
          For example: main, 2025.03.0, r23ij2o3.
      spack-manifest-path:
        required: true
        type: string
        description: |
          A file path in the inputs.spack-manifest-repository that contains the spack manifest template to install.
          For example: .github/build/manifests/template/access-om2.spack.yaml.j2.
      spack-manifest-data-path:
        required: false
        type: string
        description: |
          An optional file path in the inputs.spack-manifest-repository that contains data to fill in the spack manifest jinja template.
          This doesn't include {{ ref }}, which is filled in automatically.
          For example: .github/build/manifests/data/access-om2.spack.yaml.j2.json.
      spack-manifest-data-pairs:
        required: false
        type: string
        description: |
          An optional, multi-line string of space-separated key-value pairs to fill in inputs.spack-manifest-path.
          This is useful for filling in template values created dynamically by earlier jobs needed by this workflow.
          This doesn't include {{ ref }}, which is filled in automatically.
          For example:
          package mom5
          compiler intel
      spack-compiler-manifest-path:
        required: false
        type: string
        description: |
          A file path in the inputs.spack-manifest-repository that contains the spack manifest to install local compilers not in the upstream.
          For example: .github/build/manifests/compilers.spack.yaml.
      ref:
        required: false
        type: string
        # Since the github.sha for a pull request is the commit SHA of the merge commit (which
        # doesn't exist in the caller model component repository), we will instead use the PR HEAD SHA.
        default: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
        description: |
          The branch, tag, or commit SHA of the package under test.
          This value is filled in to the inputs.spack-manifest-path template as {{ ref }}.
          For example: main, 2025.03.0, 7ey2uy2.
      spack-config-ref:
        required: false
        type: string
        default: main
        description: |
          The branch, tag, or commit SHA of the access-nri/spack-config repository to use.
          For example: main, 2025.03.0, 7ey2uy2.
      builtin-spack-packages-ref:
        required: false
        type: string
        # default: ref from spack-config's repos.yaml, or 'develop' otherwise
        description: |
          The branch, tag, or commit SHA of the spack/spack-packages repository to use.
          For example: main, 2025.03.0, 7ey2uy2.
      access-spack-packages-ref:
        required: false
        type: string
        default: api-v2
        description: |
          The branch, tag, or commit SHA of the access-nri/spack-packages repository to use.
          For example: main, 2025.03.0, 7ey2uy2.
      spack-ref:
        required: false
        type: string
        # Default spack version - must be changed across the Dockerfile as well
        default: access/releases/v1.1
        description: |
          The branch, tag, or commit SHA of the access-nri/spack repository to use.
          For example: develop, releases/0.22, 7ey2uy2.
      pytest-test-markers:
        required: false
        type: string
        description: |
          A string of pytest markers to use to filter tests in the caller model component repository's .github/build/tests directory.
          For example: "not slow and not mpi".
      allow-ssh-into-spack-install:
        required: false
        type: boolean
        default: false
        description: |
          Enable the actor of the workflow to SSH into the container where the spack packages have been installed.
          This is useful for gathering post-install information before the container is destroyed.
          This will also make the workflow wait until the actor SSHs into the container, or it times out, before continuing.
      container-image-version:
        required: false
        type: string
        default: :rocky
        description: |
          The version of the container image to use for the runner.
          Can be either a tag (specified by ':TAG') or a SHA (specified by '@sha256:SHA').
          For example: ':8.9' or 'rocky@sha256:1234...'.
      spack-oci-buildcache-url:
        required: false
        type: string
        description: |
          The URL to an oci-backed buildcache, available in spack >= v1.0.
          OCI-backed buildcaches are the only option for GitHub-hosted CI, and can be used as a backup for self-hosted CI's runner buildcache.
          For example: 'oci://ghcr.io/ACCESS-NRI/build-ci-buildcache'.
      run-self-hosted:
        required: false
        type: boolean
        default: true
        description: |
          Whether to run the job on a self-hosted runner.
          For security, workflow runs will hang if this is true but it is not using a valid v* branch or tag for the workflow ref.
      enable-pytest:
        type: boolean
        required: false
        default: false
        description: |
          Whether to enable post-build testing of the manifest.
          All visible pytests under inputs.spack-manifest-repository will be run.
      pytest-args:
        type: string
        required: false
        description: |
          A list of pytest flags to affect the invocation of pytest. For example, addition of markers with '-m "marker_one and marker_two"'
    secrets:
      spack-install-command-pat:
        required: false
        description: |
          An optional GitHub PAT to use for the spack install command, for access to potentially private repositories.
      spack-oci-buildcache-username:
        required: false
        description: |
          A username (or GitHub username for oci://ghcr.io buildcaches) to use for reading and writing to the spack OCI buildcache, if inputs.spack-oci-buildcache-url is defined.
      spack-oci-buildcache-password:
        required: false
        description: |
          A password (or GitHub PAT for oci://ghcr.io buildcaches) to use for reading and writing to the spack OCI buildcache, if inputs.spack-oci-buildcache-url is defined.
    outputs:
      spec-concretization-graph:
        value: ${{jobs.spack-install.outputs.spec-concretization-graph }}
        description: |
          A visual representation of the dependencies and constraints of the spack manifest file installed.
      spack-manifest-repository-sha:
        value: ${{ jobs.spack-install.outputs.spack-manifest-repository-sha }}
        description: |
          The SHA of the spack manifest repository checked out.
      spack-sha:
        value: ${{ jobs.spack-install.outputs.spack-sha }}
        description: |
          The SHA of the spack repository checked out.
      spack-config-sha:
        value: ${{ jobs.spack-install.outputs.spack-config-sha }}
        description: |
          The SHA of the spack-config repository checked out.
      builtin-spack-packages-sha:
        value: ${{ jobs.spack-install.outputs.builtin-spack-packages-sha }}
        description: |
          The SHA of the builtin spack-packages repository checked out.
      access-spack-packages-sha:
        value: ${{ jobs.spack-install.outputs.access-spack-packages-sha }}
        description: |
          The SHA of the access-spack-packages repository checked out.
      caller-sha:
        value: ${{ jobs.spack-install.outputs.caller-sha }}
        description: |
          The SHA of the caller model component repository checked out.
      container-id:
        value: ${{ jobs.spack-install.outputs.container-id }}
        description: |
          The ID of the container where the spack packages have been installed.
      short-container-id:
        value: ${{ jobs.spack-install.outputs.short-container-id }}
        description: |
          The short ID of the container where the spack packages have been installed - used for artifact disambiguation.
      ## These outputs contain information on data uploaded as artifacts
      artifact-pattern:
        # This stays the same whether test-build ran, so we just take it from the first job in the workflow
        value: ${{ jobs.spack-install.outputs.artifact-pattern }}
        description: |
          Wildcard pattern to match all artifacts across a matrix job.
      artifact-url:
        # The artifact url may change if test-build ran and overwrote it - so we take the one from test-build if it exists, and otherwise take it from spack-install
        value: ${{ jobs.test-build.outputs.artifact-url || jobs.spack-install.outputs.artifact-url }}
        description: |
          The URL of the artifact, which contains all outputs of the job.
          This contains spack files and outputs of the job itself for post-matrix processing.
env:
  # Common directory for outputs to be added to artifact
  artifact-content-dir: /tmp/artifact-output
jobs:
  spack-install:
    name: Install
    runs-on: ${{ inputs.run-self-hosted && fromJson('{"group":"build-ci"}') || 'ubuntu-latest' }}
    container:
      image: ghcr.io/access-nri/build-ci-runner${{ inputs.container-image-version }}
      volumes:
        # For self-hosted runners, mount the proper upstream and buildcache volumes from the kubernetes cluster
        # For GitHub-hosted runners, mount the dummy volume /dev/null to avoid errors or undefined behavior, eg. fromJson('[]')
        - ${{ inputs.run-self-hosted && '/opt/upstream-v1:/opt/release:ro' || '/dev/null:/dev/null:ro' }}
        - ${{ inputs.run-self-hosted && '/opt/runner_set_buildcache:/opt/runner_set_buildcache:rw' || '/dev/null:/dev/null:ro' }}
    outputs:
      # Job outputs outputted as workflow output
      spec-concretization-graph: ${{ steps.install.outputs.spec }}
      spack-manifest-repository-sha: ${{ steps.checkout.outputs.commit }}
      spack-sha: ${{ steps.setup.outputs.spack-sha }}
      spack-config-sha: ${{ steps.setup.outputs.spack-config-sha }}
      builtin-spack-packages-sha: ${{ steps.setup.outputs.builtin-spack-packages-sha }}
      access-spack-packages-sha: ${{ steps.setup.outputs.access-spack-packages-sha }}
      caller-sha: ${{ steps.checkout-caller.outputs.commit }}
      artifact-pattern: ${{ steps.init.outputs.artifact-pattern }}
      artifact-url: ${{ steps.upload.outputs.artifact-url }}
      container-id: ${{ steps.init.outputs.container-id }}
      short-container-id: ${{ steps.init.outputs.short-container-id }}
      # Job outputs only used in the test job
      artifact-name: ${{ steps.init.outputs.artifact-name }}
    steps:
      - name: Init - Clone build-ci for custom actions
        uses: actions/checkout@v6
        with:
          repository: access-nri/build-ci
          ref: ${{ job.workflow_sha }}
          path: build-ci

      - name: Init - Initalize workflow vars
        id: init
        # GitHub Actions doesn't allow expressions in the on.workflow_call.inputs.*.default section, so we need to define them here
        # Furthermore, some outputs depend on the container being started, so we define them here as well
        run: |
          # Initializing dynamic default of inputs.spack-manifest-repository-ref...

          if [[ "${{ inputs.spack-manifest-repository-ref }}" != "" ]]; then
            spack_manifest_repository_ref=${{ inputs.spack-manifest-repository-ref }}
          elif [[ "${{ inputs.spack-manifest-repository }}" == "${{ github.repository }}" ]]; then
            if [[ "${{ github.event_name }}" == "pull_request" ]]; then
              spack_manifest_repository_ref=${{ github.event.pull_request.head.sha }}
            else
              spack_manifest_repository_ref=${{ github.sha }}
            fi
          fi

          echo "spack-manifest-repository-ref: $spack_manifest_repository_ref"
          echo "spack-manifest-repository-ref=$spack_manifest_repository_ref" >> $GITHUB_OUTPUT

          # Initializing container id and associated artifact globs/filenames...
          container_id=${{ job.container.id }}
          short_container_id=${container_id:0:8}

          echo "::notice::Short Container ID used for artifacts in this job: $short_container_id"

          # We can only get the job.container.id after the container is started, so we set it as the file name here
          echo "artifact-name=output-$short_container_id" >> $GITHUB_OUTPUT
          echo "artifact-pattern=output-*" >> $GITHUB_OUTPUT

          echo "container-id=$container_id" >> $GITHUB_OUTPUT
          echo "short-container-id=$short_container_id" >> $GITHUB_OUTPUT

      - name: Setup - Setup and Update Instance
        id: setup
        uses: build-ci/.github/actions/setup-instance
        with:
          spack-ref: ${{ inputs.spack-ref }}
          spack-config-ref: ${{ inputs.spack-config-ref }}
          builtin-spack-packages-ref: ${{ inputs.builtin-spack-packages-ref }}
          access-spack-packages-ref: ${{ inputs.access-spack-packages-ref }}
          spack-oci-buildcache-url: ${{ inputs.spack-oci-buildcache-url }}
          run-self-hosted: ${{ inputs.run-self-hosted }}

      - name: Manifest - Checkout Caller ${{ github.repository }}
        id: checkout-caller
        uses: actions/checkout@v6
        with:
          # The default ref is the merge commit for pull requests, which isn't able to be checked out locally
          # (and is therefore useless outside of the workflow run), so we get the PR head instead. See https://github.com/orgs/community/discussions/26325
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          submodules: recursive
          path: caller

      - name: Manifest - Checkout Manifest From ${{ inputs.spack-manifest-repository }}
        id: checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.spack-manifest-repository }}
          ref: ${{ steps.setup.outputs.spack-manifest-repository-ref }}
          # Only checkout the manifests, rather than the entire repository
          path: manifest
          sparse-checkout-cone-mode: false
          sparse-checkout: |-
            ${{ inputs.spack-manifest-path }}
            ${{ inputs.spack-manifest-data-path }}
            ${{ inputs.spack-compiler-manifest-path }}
          # Similarly to the spack install command below, we need to be able to checkout the spack-manifest-repository (which may be private)
          token: ${{ secrets.spack-install-command-pat || github.token }}

      - name: Manifest - Delete History From ${{ inputs.spack-manifest-repository }}
        # Specifically, this is to avoid exposing a private spack manifest repository's history to the actor if they SSH in
        working-directory: manifest
        if: always() && steps.checkout.conclusion == 'success'
        run: rm -rf ./.git

      - name: Manifest - Install Compilers Locally
        # Some compilers may not be available upstream, so we install them locally in a separate spack.yaml
        if: inputs.spack-compiler-manifest-path != ''
        id: compilers
        working-directory: manifest
        env:
          # For pulling OCI buildcache
          OCI_USERNAME: ${{ secrets.spack-oci-buildcache-username || github.actor }}
          OCI_PASSWORD: ${{ secrets.spack-oci-buildcache-password || secrets.GITHUB_TOKEN }}
        run: |
          . ${{ steps.setup.outputs.SPACK_ROOT }}/share/spack/setup-env.sh
          spack env activate local_compilers --create --prompt --envfile ${{ inputs.spack-compiler-manifest-path }}

          spack --debug install --fail-fast --deprecated
          spack env deactivate

          spack compiler list

      - name: Manifest - Push Local Compilers to Buildcache
        env:
          # For pulling and pushing OCI buildcache
          # If secrets.GITHUB_TOKEN has permissions.packages:write, one would not have to specify secrets.spack-oci-buildcache-password
          OCI_USERNAME: ${{ secrets.spack-oci-buildcache-username || github.actor }}
          OCI_PASSWORD: ${{ secrets.spack-oci-buildcache-password || secrets.GITHUB_TOKEN }}
        if: inputs.spack-oci-buildcache-url != '' && steps.compilers.outcome == 'success'
        run: |
          . ${{ steps.setup.outputs.SPACK_ROOT }}/share/spack/setup-env.sh
          spack -e local_compilers buildcache push --unsigned --private oci_buildcache

      - name: Manifest - Install jinja-cli
        run: python3 -m pip install jinja-cli==1.2.2

      - name: Manifest - Replace jinja template variables
        # This means that the caller manifest files can remain unchanged, but still vary based on the {{ pr }}
        # Additional data can be provided to fill in the jinja template through the `spack-manifest-data-path` input
        id: jinja-templated
        working-directory: manifest
        run: |
          templated_manifest_path=$(dirname ${{ inputs.spack-manifest-path }})/templated/$(basename ${{ inputs.spack-manifest-path }} .j2)
          mkdir -p $(dirname $templated_manifest_path)

          jinja \
            --define ref ${{ inputs.ref }} \
            $( [ -n "${{ inputs.spack-manifest-data-pairs }}" ] && while read -r d; do echo "--define $d"; done <<< "${{ inputs.spack-manifest-data-pairs }}") \
            ${{ inputs.spack-manifest-data-path != '' && format('--data {0}', inputs.spack-manifest-data-path) || '' }} \
            ${{ inputs.spack-manifest-path}} \
            > $templated_manifest_path

          echo "Templated manifest at $templated_manifest_path is:"
          cat $templated_manifest_path

          echo "spack-manifest-path=$templated_manifest_path" >> $GITHUB_OUTPUT

      - name: Manifest - Install
        id: install
        working-directory: manifest
        env:
          # For pulling OCI buildcache
          OCI_USERNAME: ${{ secrets.spack-oci-buildcache-username || github.actor }}
          OCI_PASSWORD: ${{ secrets.spack-oci-buildcache-password || secrets.GITHUB_TOKEN }}
          # This is needed to ensure that the spack install command can access private repositories - we replace all HTTPS git URLs with the PAT
          # We set the git config via environment variables, so that the PATs are not persisted in the container
          GIT_CONFIG_COUNT: 1
          GIT_CONFIG_KEY_0: url.https://oauth2:${{ secrets.spack-install-command-pat || secrets.GITHUB_TOKEN }}@github.com/.insteadOf
          GIT_CONFIG_VALUE_0: https://github.com/
        run: |
          . ${{ steps.setup.outputs.SPACK_ROOT }}/share/spack/setup-env.sh
          spack env create default ${{ steps.jinja-templated.outputs.spack-manifest-path }}
          spack env activate

          spack concretize --force

          echo "spec<<EOF" >> $GITHUB_OUTPUT
          echo "$(spack spec)" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Output config before install for debugging
          echo "::group::Spack Config Blame Output"
          spack config blame
          echo "::endgroup::"

          spack --debug install --fail-fast --deprecated

      - name: Manifest - Push to Buildcache
        env:
          # For pulling and pushing OCI buildcache
          # If secrets.GITHUB_TOKEN has permissions.packages:write, one would not have to specify secrets.spack-oci-buildcache-password
          OCI_USERNAME: ${{ secrets.spack-oci-buildcache-username || github.actor }}
          OCI_PASSWORD: ${{ secrets.spack-oci-buildcache-password || secrets.GITHUB_TOKEN }}
        if: inputs.spack-oci-buildcache-url != ''
        run: |
          . ${{ steps.setup.outputs.SPACK_ROOT }}/share/spack/setup-env.sh
          spack -e default buildcache push --unsigned --only=dependencies oci_buildcache

      - name: Tmate - Create session
        # Only create the session if the spack installation was attempted, and we want a tmate session
        if: >-
          always() &&
          (steps.install.conclusion == 'failure' || steps.install.conclusion == 'success') &&
          inputs.allow-ssh-into-spack-install
        id: tmate
        uses: mxschmitt/action-tmate@e5c7151931ca95bad1c6f4190c730ecf8c7dde48  # v3.19
        with:
          # sudo is not accessible in this container
          sudo: false
          # allow future steps to run without awaiting tmate session close
          detached: true
          # Only allow actor to access the tmate session
          limit-access-to-actor: true
          # Our runner container has tmate pre-installed
          install-dependencies: false

      - name: Outputs - Consolidate Spack Outputs
        if: always() && (steps.install.conclusion == 'failure' || steps.install.conclusion == 'success')
        # Logs or manifests may not be available if the spack install failed before concretization, so we'd rather direct users to the
        # above install failure than have this step fail.
        continue-on-error: true
        run: |
          # Consolidate Manifests
          if compgen -G "${{ steps.setup.outputs.spack-env-dir }}/default/spack.*" > /dev/null; then
            cp -v ${{ steps.setup.outputs.spack-env-dir }}/default/spack.* ${{ env.artifact-content-dir }}
          fi

          if compgen -G "${{ steps.setup.outputs.spack-env-dir }}/local_compilers/spack.*" > /dev/null; then
            mkdir -p ${{ env.artifact-content-dir }}/local_compilers
            cp -v ${{ steps.setup.outputs.spack-env-dir }}/local_compilers/spack.* ${{ env.artifact-content-dir }}/local_compilers
          fi

          # Consolidate Logs
          . ${{ steps.setup.outputs.SPACK_ROOT }}/share/spack/setup-env.sh

          if [ ! -f ${{ steps.setup.outputs.spack-env-dir }}/default/spack.lock ]; then
            echo "Spack lock file not found, skipping log creation."
            exit 0
          fi

          # Get all the top-level hashes from the manifest
          hashes="$(jq --raw-output '.roots[].hash' ${{ steps.setup.outputs.spack-env-dir }}/default/spack.lock)"
          echo "Found top-level hashes:"
          echo "$hashes"

          i=0
          while read -r hash; do
            spack -e default logs /$hash > "${{ env.artifact-content-dir }}/spec_install_log_${i}.log" || true
            i=$((i + 1))
          done <<< "$hashes"

      - name: Outputs - Consolidate Job Outputs
        if: always() && (steps.install.conclusion == 'failure' || steps.install.conclusion == 'success')
        # The outputs of the job also contain the inputs to the job, so that they can be used in future jobs.
        # We need to serialize the spec concretization graph and data pairs to a single line, so that it can be used in JSON.
        run: |
          serialized_spec_concretization_graph=$(echo "${{ steps.install.outputs.spec }}" | sed -z 's/\n/\\n/g')
          serialized_spack_manifest_data_pairs=$(echo ${{ inputs.spack-manifest-data-pairs }} | sed -z 's/\n/\\n/g')

          jq --null-input \
             --arg spec "$serialized_spec_concretization_graph" \
             --arg pairs "$serialized_spack_manifest_data_pairs" \
          '{
            "spack_manifest_path": "${{ inputs.spack-manifest-path }}",
            "spack_manifest_repository": "${{ inputs.spack-manifest-repository }}",
            "spack_manifest_repository_ref": "${{ steps.setup.outputs.spack-manifest-repository-ref }}",
            "spack_manifest_data_path": "${{ inputs.spack-manifest-data-path }}",
            "spack_manifest_data_pairs": $pairs,
            "spack_compiler_manifest_path": "${{ inputs.spack-compiler-manifest-path }}",
            "ref": "${{ inputs.ref }}",
            "spack_config_ref": "${{ inputs.spack-config-ref }}",
            "builtin_spack_packages_ref": "${{ inputs.builtin-spack-packages-ref }}",
            "access_spack_packages_ref": "${{ inputs.access-spack-packages-ref }}",
            "spack_ref": "${{ inputs.spack-ref }}",
            "pytest_test_markers": "${{ inputs.pytest-test-markers }}",
            "allow_ssh_into_spack_install": "${{ inputs.allow-ssh-into-spack-install }}",
            "container_image_version": "${{ inputs.container-image-version }}",
            "run_self_hosted": "${{ inputs.run-self-hosted }}",

            "spack_install_result": "${{ steps.install.conclusion }}",

            "spec_concretization_graph": $spec,
            "spack_manifest_repository_sha": "${{ steps.checkout.outputs.commit }}",
            "spack_sha": "${{ steps.setup.outputs.spack-sha }}",
            "spack_config_sha": "${{ steps.setup.outputs.spack-config-sha }}",
            "builtin_spack_packages_sha": "${{ steps.setup.outputs.builtin-spack-packages-sha }}",
            "access_spack_packages_sha": "${{ steps.setup.outputs.access-spack-packages-sha }}",
            "caller_sha": "${{ steps.checkout-caller.outputs.commit }}",
            "container_id": "${{ steps.init.outputs.container-id }}",
            "short_container_id": "${{ steps.init.outputs.short-container-id }}",
            "artifact_pattern": "${{ steps.init.outputs.artifact-pattern }}"
          }' > ${{ env.artifact-content-dir }}/job_outputs.json

      - name: Outputs - Upload
        if: always() && (steps.install.conclusion == 'failure' || steps.install.conclusion == 'success')
        id: upload
        uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.init.outputs.artifact-name }}
          path: ${{ env.artifact-content-dir }}
          if-no-files-found: error

  test-build:
    name: Test
    runs-on: ${{ inputs.run-self-hosted && fromJson('{"group":"build-ci"}') || 'ubuntu-latest' }}
    needs:
      - spack-install
    if: inputs.enable-pytest
    container:
      image: ghcr.io/access-nri/build-ci-runner${{ inputs.container-image-version }}
      volumes:
        # For self-hosted runners, mount the proper upstream and buildcache volumes from the kubernetes cluster
        # For GitHub-hosted runners, mount the dummy volume /dev/null to avoid errors or undefined behavior, eg. fromJson('[]')
        - ${{ inputs.run-self-hosted && '/opt/upstream-v1:/opt/release:ro' || '/dev/null:/dev/null:ro' }}
        - ${{ inputs.run-self-hosted && '/opt/runner_set_buildcache:/opt/runner_set_buildcache:rw' || '/dev/null:/dev/null:ro' }}
    outputs:
      artifact-url: ${{ steps.upload.outputs.artifact-url }}
      tests-passed: ${{ steps.test.outputs.passed }}
      tests-failed: ${{ steps.test.outputs.failed }}
      tests-error: ${{ steps.test.outputs.error }}
      tests-total: ${{ steps.test.outputs.total }}
    steps:
      - name: Init - Clone build-ci for custom actions
        uses: actions/checkout@v6
        with:
          repository: access-nri/build-ci
          ref: ${{ job.workflow_sha }}
          path: build-ci

      - name: Setup - Setup and Update Instance
        id: setup
        uses: build-ci/.github/actions/setup-instance
        with:
          spack-ref: ${{ inputs.spack-ref }}
          spack-config-ref: ${{ inputs.spack-config-ref }}
          builtin-spack-packages-ref: ${{ inputs.builtin-spack-packages-ref }}
          access-spack-packages-ref: ${{ inputs.access-spack-packages-ref }}
          spack-oci-buildcache-url: ${{ inputs.spack-oci-buildcache-url }}
          run-self-hosted: ${{ inputs.run-self-hosted }}

      - name: Manifest - Checkout Caller ${{ github.repository }}
        id: checkout-caller
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          submodules: recursive
          path: caller

      - name: Manifest - Checkout Manifest From ${{ inputs.spack-manifest-repository }}
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.spack-manifest-repository }}
          ref: ${{ needs.spack-install.outputs.spack-manifest-repository-sha }}
          # Only checkout the manifests, rather than the entire repository
          path: manifest
          sparse-checkout-cone-mode: false
          sparse-checkout: |-
            ${{ inputs.spack-manifest-path }}
            ${{ inputs.spack-manifest-data-path }}
            ${{ inputs.spack-compiler-manifest-path }}
          # Similarly to the spack install command below, we need to be able to checkout the spack-manifest-repository (which may be private)
          token: ${{ secrets.spack-install-command-pat || github.token }}

      - name: Download Install Artifact
        id: download-install-artifact
        uses: actions/download-artifact@v6
        with:
          name: ${{ needs.spack-install.outputs.artifact-name }}
          path: ${{ env.artifact-content-dir }}

      - name: Manifest - Install Compilers Locally
        # Some compilers may not be available upstream, so we install them locally in a separate spack.yaml
        if: inputs.spack-compiler-manifest-path != ''
        env:
          # For pulling OCI buildcache
          OCI_USERNAME: ${{ secrets.spack-oci-buildcache-username || github.actor }}
          OCI_PASSWORD: ${{ secrets.spack-oci-buildcache-password || secrets.GITHUB_TOKEN }}
        run: |
          . ${{ steps.setup.outputs.SPACK_ROOT }}/share/spack/setup-env.sh
          spack env activate local_compilers --create --prompt --envfile ${{ env.artifact-content-dir }}/local_compilers/spack.lock
          spack --debug install --fail-fast --deprecated --use-cache
          spack env deactivate
          yq '.spack.specs[]' ${{ env.artifact-content-dir }}/local_compilers/spack.lock | while read compiler; do
            spack load $compiler
            spack compiler find --scope=user
          done
          spack compiler list

      - name: Manifest - Install
        env:
          # For pulling OCI buildcache
          OCI_USERNAME: ${{ secrets.spack-oci-buildcache-username || github.actor }}
          OCI_PASSWORD: ${{ secrets.spack-oci-buildcache-password || secrets.GITHUB_TOKEN }}
          # This is needed to ensure that the spack install command can access private repositories - we replace all HTTPS git URLs with the PAT
          # We set the git config via environment variables, so that the PATs are not persisted in the container
          GIT_CONFIG_COUNT: 1
          GIT_CONFIG_KEY_0: url.https://oauth2:${{ secrets.spack-install-command-pat || secrets.GITHUB_TOKEN }}@github.com/.insteadOf
          GIT_CONFIG_VALUE_0: https://github.com/
        run: |
          . ${{ steps.setup.outputs.SPACK_ROOT }}/share/spack/setup-env.sh
          spack env activate default --create --prompt --envfile ${{ env.artifact-content-dir }}/spack.lock
          spack --debug install --fail-fast --deprecated --use-cache

      - name: Test - Install pytest
        run: python3 -m pip install pytest pytest-json-report

      - name: Test - Pytest
        id: test
        run: |
          report_path=${{ env.artifact-content-dir }}/pytest_report.json
          echo "report-path=$report_path" >> $GITHUB_OUTPUT

          . ${{ steps.setup.outputs.SPACK_ROOT }}/share/spack/setup-env.sh
          spack env activate default
          pytest ${{ inputs.pytest-args }} --json-report --json-report-file=$report_path

      - name: Test - Results
        id: results
        if: always() && steps.test.outcome != 'skipped'
        run: |
          echo "passed=$(jq --raw-output '.summary.passed // 0' ${{ steps.test.outputs.report-path }})" >> $GITHUB_OUTPUT
          echo "failed=$(jq --raw-output '.summary.failed // 0' ${{ steps.test.outputs.report-path }})" >> $GITHUB_OUTPUT
          echo "error=$(jq --raw-output '.summary.error // 0' ${{ steps.test.outputs.report-path }})" >> $GITHUB_OUTPUT
          echo "total=$(jq --raw-output '.summary.total // 0' ${{ steps.test.outputs.report-path }})" >> $GITHUB_OUTPUT

      - name: Outputs - Consolidate Job Outputs
        if: always() && steps.test.outcome != 'skipped'
        run: |
          jq --null-input \
            --slurpfile outputs ${{ env.artifact-content-dir }}/job_outputs.json \
            '$outputs[] + {
              "test_build_result" : "${{ steps.test.outcome }}",
              "tests_passed": ${{ steps.results.outputs.passed }},
              "tests_failed": ${{ steps.results.outputs.failed }},
              "tests_error": ${{ steps.results.outputs.error }},
              "tests_total": ${{ steps.results.outputs.total }}
            }' \
            > ${{ env.artifact-content-dir }}/job_outputs.json.tmp

          mv ${{ env.artifact-content-dir }}/job_outputs.json.tmp ${{ env.artifact-content-dir }}/job_outputs.json

      - name: Outputs - Upload
        if: always()
        id: upload
        uses: actions/upload-artifact@v6
        with:
          name: ${{ needs.spack-install.outputs.artifact-name }}
          path: ${{ env.artifact-content-dir }}
          if-no-files-found: error
          # As we're recreating the artifact with the additional test outputs,
          # we need to overwrite the artifact uploaded by the install job
          overwrite: true
