name: Notification of spack_packages update
on:
  workflow_dispatch:
    inputs:
      spack-packages-version:
        type: string
        required: true
        default: main
        description: "Either a git tag or branch name for the ACCESS-NRI/spack_packages repository, which defaults to the main branch"
      packages:
        type: string
        required: true
        description: "packages from spack_packages that needs to be rebuilt"

jobs:
  update-spack-base-image:
    uses: access-nri/workflows/.github/workflows/build-and-push-image.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/base-spack-${{ github.event.inputs.spack-packages-version }}
      dockerfile-directory: containers
      dockerfile-name: Dockerfile.base-spack
      build-args: "SPACK_PACKAGES_VERSION=${{ github.event.inputs.spack-packages-version }}"
    secrets:
      build-secrets: |
        "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}"
        "S3_ACCESS_KEY_SECRET=${{ secrets.S3_ACCESS_KEY_SECRET }}"
        "access-nri.priv=${{ secrets.BUILDCACHE_KEY_PRIVATE }}"
        "access-nri.pub=${{ secrets.BUILDCACHE_KEY_PUBLIC }}"
    permissions:
      contents: read
      packages: write

  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.generate.outputs.packages }}
      compilers: ${{ steps.generate.outputs.compilers }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - name: Generate model matrix
        id: generate
        run: python ./util/matrix_generation.py ${{ github.event.inputs.packages }}

  update-image-builds:
    needs:
      - update-spack-base-image
      - generate-matrix
    strategy:
      matrix: 
        package: ${{ fromJson(needs.generate-matrix.outputs.packages) }}
        compiler: ${{ fromJson(needs.generate-matrix.outputs.compilers) }}

    uses: access-nri/workflows/.github/workflows/build-and-push-image.yml@main
    with:
      container-registry: ghcr.io
      container-name: access-nri/build-${{ matrix.package }}-${{ matrix.compiler.name }}${{ matrix.compiler.version }}-${{ github.event.inputs.spack-packages-version }}
      dockerfile-directory: containers
      dockerfile-name: Dockerfile.build
      build-args: |
        # TODO: Probably shouldn't hard code base image path
        "BASE_IMAGE=ghcr.io/access-nri/base-spack-${{ github.event.inputs.spack-packages-version }}:latest"
        "PACKAGE=${{ matrix.package }}"
        "COMPILER_NAME=${{ matrix.compiler.name}}"
        "COMPILER_PACKAGE=${{ matrix.compiler.package}}"
        "COMPILER_VERSION=${{ matrix.compiler.version}}"
    secrets:
      build-secrets: |
        "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}"
        "S3_ACCESS_KEY_SECRET=${{ secrets.S3_ACCESS_KEY_SECRET }}"
        "access-nri.priv=${{ secrets.BUILDCACHE_KEY_PRIVATE }}"
        "access-nri.pub=${{ secrets.BUILDCACHE_KEY_PUBLIC }}"
    permissions: 
      contents: read
      packages: write


