name: Recover buildcache keys

on:
  workflow_dispatch:

jobs:
  recover-keys:
    name: Recover keys
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          BUILDCACHE_KEY_PRIVATE: ${{ secrets.BUILDCACHE_KEY_PRIVATE }}
          BUILDCACHE_KEY_PUBLIC: ${{ secrets.BUILDCACHE_KEY_PUBLIC }}
          OPENSSL_PASSWORD: ${{ secrets.OPENSSL_PASSWORD }}
          OPENSSL_ITER: ${{ secrets.OPENSSL_ITER }}
        run: |
          echo "BUILDCACHE_KEY_PRIVATE (openssl) = $(echo "${BUILDCACHE_KEY_PRIVATE}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
          echo "BUILDCACHE_KEY_PUBLIC (openssl) = $(echo "${BUILDCACHE_KEY_PUBLIC}" | openssl enc -e -aes-256-cbc -a -pbkdf2 -iter ${OPENSSL_ITER} -k "${OPENSSL_PASSWORD}")"
