name: Scheduled Cache Eviction
on:
  schedule:
    - cron: 30 2 3 * *
jobs:
  eviction:
    permissions:
      packages: write
    uses: ./.github/workflows/github-cache-eviction.yml
    with:
      buildcache-package-org: ${{ github.repository_owner }}
      buildcache-package-name: build-ci-buildcache
      eviction-threshold-days: 90
    secrets:
      token: ${{ secrets.SPACK_CACHE_PACKAGE_EVICTION_PAT }}
